[package]
name = "file_info"
version = "0.1.0"
edition = "2021"

[dependencies]
authenticode = "0.4.3"
goblin = { version = "0.8.2" }
exe = "0.5.6"
hex = "0.4.3"
serde = { version = "1.0.210", features = ["derive"] }
entropy = "0.4.2"
phf = { version="0.11.2" , features = ["macros"] }
pkbuffer = "0.4.1"
bytemuck = "1.19.0"
cms = { version = "0.2.0", default-features = false }

[features]
serde = ["serde/derive"]